[package]
name = "age-env"
version = "0.1.15"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
clap_complete = "4.5.7"
dotenv-parser = "0.1.3"
which = "6.0.1"

[[bin]]
name = "age-env"
path = "src/main.rs"
